import { Dela_Gothic_One } from "next/font/google";
import { David_Libre } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

const dela = Dela_Gothic_One({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Deja Brew</title>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/icons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/favicon-16x16.png"
        />
        <link rel="shortcut icon" href="/icons/favicon.ico" />
        <meta name="description" content="Coffee that speaks of HOME." />
        <meta
          name="keywords"
          content="Coffee, Beans, Coffee Shop, Cafe, Espresso"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#243665" />
        <meta name="og:title" property="og:title" content="Deja Brew" />
        <meta
          name="og:description"
          property="og:description"
          content="Coffee that speaks of HOME."
        />
        <meta name="image" property="image" content="/og.png" />
        <meta name="og:image" property="og:image" content="/og.png" />
        <meta
          name="og:url"
          property="og:url"
          content="https://dejabrew.rvnt.in"
        />
        <meta name="og:site_name" property="og:site_name" content="Deja Brew" />
        <meta name="og:type" property="og:type" content="website" />
        <meta name="og:locale" property="og:locale" content="en_IN" />
        <meta
          name="og:locale:alternate"
          property="og:locale:alternate"
          content="en_US"
        />
        <meta
          name="twitter:card"
          property="twitter:card"
          content="summary_large_image"
        />
        <meta name="twitter:creator" content="@dejabrewcafe" />
        <meta name="twitter:title" content="Deja Brew" />
        <meta
          name="twitter:description"
          content="Coffee that speaks of HOME."
        />
        <meta name="twitter:image" content="/og.png" />
      </head>
      <body className={dela.className}>
        <NavBar></NavBar>
        <div className="bigboody">
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
